#!/bin/bash

while :
do
    echo "Attention est tu sur de vouloir executer le programe ? Il contient du contenu interdit par 42"
    echo "Tu as 1 minute pour fermer la fenetre"
    sleep 50
    sleep 10
    open "https://fr.pornhub.com"
    open "https://fr.pornhub.com"
    open "https://fr.pornhub.com"
    open "https://fr.pornhub.com"
    open "https://static.wikia.nocookie.net/villainsfanon/images/4/4e/Troll-Face-Meme-PNG.png/revision/latest?cb=20190104124219"
done